// src/components/ReportDocument.jsx
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import DejaVu from "../assets/fonts/DejaVuSans.ttf";

Font.register({
  family: "DejaVuSans",
  src: DejaVu,
});

// 🖋️ Use built-in Helvetica for simplicity
const styles = StyleSheet.create({
  page: {
    fontFamily: "DejaVuSans",
    padding: 32,
    fontSize: 11,
    color: "#111827",
  },
  header: { textAlign: "center", marginBottom: 20 },
  title: { fontSize: 20, fontWeight: "bold", color: "#4338CA" },
  subtitle: { fontSize: 14, marginTop: 4, color: "#4B5563" },
  section: { marginVertical: 12 },
  sectionTitle: { fontSize: 14, marginBottom: 6, color: "#4338CA" },

  // Summary bar styles
  themeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  themeLabel: { width: "40%", fontWeight: "bold" },
  barContainer: {
    flex: 1,
    height: 8,
    backgroundColor: "#E5E7EB",
    borderRadius: 4,
    marginHorizontal: 6,
  },
  barFill: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#6366F1",
  },
  percentText: { width: "15%", textAlign: "right" },

  overall: { textAlign: "center", marginVertical: 20 },

  // Question table layout
  questionHeader: {
    flexDirection: "row",
    backgroundColor: "#EEF2FF",
    borderBottomWidth: 1,
    borderBottomColor: "#CBD5E1",
    padding: 4,
  },
  questionHeaderText: {
    fontWeight: "bold",
    fontSize: 11,
  },
  questionRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#E5E7EB",
    paddingVertical: 3,
  },
  questionCol: {
    width: "70%",
    paddingRight: 6,
  },
  answerCol: {
    width: "30%",
    textAlign: "right",
  },
  footer: { textAlign: "center", marginTop: 20, fontSize: 10, color: "#6B7280" },
});

export default function ReportDocument({ results }) {
  return (
    <Document>
      <Page style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Mastering Money Report</Text>
          <Text style={styles.subtitle}>Your Personalised Results</Text>
        </View>

        {/* Overall Summary */}
        <View style={styles.overall}>
          <Text style={{ fontSize: 16 }}>
            Overall Score: {results.overallPercent}%
          </Text>
          <Text style={{ fontSize: 14 }}>Rating: {results.ratingForReport}</Text>
        </View>

        {/* Summary Chart */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Theme Summary</Text>
          {results.themes?.map((t) => (
            <View key={t.themeId} style={styles.themeRow}>
              <Text style={styles.themeLabel}>{t.themeName}</Text>
              <View style={styles.barContainer}>
                <View style={[styles.barFill, { width: `${t.percent}%` }]} />
              </View>
              <Text style={styles.percentText}>{t.percent}%</Text>
            </View>
          ))}
        </View>

        {/* Detailed Questions */}
        {results.themes?.map((theme) => (
          <View key={theme.themeId} style={styles.section}>
            <Text style={styles.sectionTitle}>{theme.themeName}</Text>

            {/* Table Header */}
            <View style={styles.questionHeader}>
              <Text style={[styles.questionHeaderText, { width: "70%" }]}>
                Question
              </Text>
              <Text
                style={[
                  styles.questionHeaderText,
                  { width: "30%", textAlign: "right" },
                ]}
              >
                Answer (Score)
              </Text>
            </View>

            {/* Table Rows */}
            {theme.questions?.map((q) => (
              <View key={q.id} style={styles.questionRow}>
                <Text style={styles.questionCol}>{q.text}</Text>
                <Text style={styles.answerCol}>
                  {q.selectedLabel} ({q.score})
                </Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by Mastering Money App — {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
